# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sXQ01yrLbXQtUWglb42gp6X1CSZ_q-Sv
"""

import streamlit as st

st.write("""
# Hello World!
This is my **First** *app*
""")